### ISSUE TITLE
Rewrite the ProcessManager to simplify each functionnality

### ISSUE THREAD

**Issue by shavounet** [cleverage/process-bundle#88]
## Tasks

* [ ] Add an interface
* [ ] Do the event dispatching (see #83) with a decoration (is it a good idea ?)
* [ ] Return some object containing all metadata
* [ ] Explode some parts into other services (initialization / check / resolve + process / finalization ...)
